
pretrained_base_model_path: ./pretrained_weights/stable-diffusion-v1-5/
pretrained_vae_path: ./pretrained_weights/sd-vae-ft-mse
image_encoder_path: ./pretrained_weights/image_encoder
inference_config: ./configs/inference/inference_v2.yaml
data_type: video
weight_dtype: fp16
no_camera: false

camera_pose_encoder_path:
denoising_unet_path:
motion_module_path: 
pose_guider_path: 
reference_unet_path: 

test_cases:
  ./data/tiktok/test/videos/:
    - ./data/tiktok/test/dwpose


